version: '3'
services:
  docker-fe:
    image: "apache/doris:1.2.2-fe-x86_64"
    container_name: "doris-fe"
    hostname: "fe1"
    environment:
      - FE_SERVERS=fe1:172.30.80.2:9010
      - FE_ID=1
    ports:
      - 8030:8030
      - 9030:9030
    volumes:
      - ./data/doris/fe/doris-meta:/opt/apache-doris/fe/doris-meta
      - ./data/doris/fe/conf:/opt/apache-doris/fe/conf
      - ./data/doris/fe/log:/opt/apache-doris/fe/log
    logging:
      options:
        max-size: '500m'
       
    networks:
      doris_net:
        ipv4_address: 172.30.80.2
  docker-be:
    image: "apache/doris:1.2.2-be-x86_64"  # use apache/doris:1.2.1-be-x86_64-noavx2, if CPU does not support AVX2
    container_name: "doris-be"
    hostname: "be"
    depends_on:
      - docker-fe
    environment:
      - FE_SERVERS=fe1:172.30.80.2:9010
      - BE_ADDR=172.30.80.3:9050
    ports:
      - 8040:8040
    volumes:
      - ./data/doris/be/storage:/opt/apache-doris/be/storage
      - ./data/doris/be/conf:/opt/apache-doris/be/conf
      - ./data/doris/be/script:/docker-entrypoint-initdb.d
      - ./data/doris/be/log:/opt/apache-doris/be/log
    logging:
      options:
        max-size: '500m'
    networks:
      doris_net:
        ipv4_address: 172.30.80.3

networks:
  doris_net:
    ipam:
      config:
        - subnet: 172.30.80.0/16
